<a href="https://colab.research.google.com/github/zar55/COSC_640_Intro_to_AI/blob/Lab/Lab_04_zziauddin1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# COSC-640: Lab 4

**Zargham Ziauddin**

[PLACEHOLDER_FOR_NOTEBOOK_LINK]


## Getting Started

Follow the instructions below to copy this notebook and to perform some initial setup.

1. Copy this notebook by selecting `File > Save a copy in Drive`.
2. A new window should open for the copied notebook. Move the new notebook to your course folder in Google Drive by selecting `File > Move` and then selecting the desired folder.
3. Update the name of the notebook by removing "Copy of" and replacing "Username" with your actual username.
4. Update the first cell in the notebook by specifying your course number (440 or 640) and by replacing "**Student Name**" with your actual name.
5. Do not edit the line that says `PLACEHOLDER_FOR_NOTEBOOK_LINK`. This will be used by the [Notebook Renderer](https://colab.research.google.com/drive/1CJTipys46ldZxJFwnt7XbdjQUfkmoXeU?usp=sharing) tool to insert a link to your Colab notebook.
6. Enable link sharing for your notebook.

## Preparing the Colab Environment

Run the cell below to download the `aitools` course package.

In [ ]:
%%capture
!rm aitools -r
!git clone https://github.com/drbeane/aitools.git

Run the cells below to import the necessary tools for this assignment. No other import statements are required for this lab, and no other import statements should be included in this assignment.

In [ ]:
import sys
sys.path.append('../')

import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

# Import Search Algorithms
from aitools.algs import depth_first_search, breadth_first_search, uniform_cost_search
from aitools.algs import general_search, greedy_best_first, astar_search
from aitools.algs import GeneticAlgorithm

# Import Environments
from aitools.envs import Knapsack, JobAssignment

np.set_printoptions(linewidth=120)

# Part 1: Knapsack Problem

In Part 1, you will apply the genetic algorithm to a Knapsack problem with 3 constraints.

## 1.A - Create Environment

Create an instance of the `Knapsack` environment with 100 items and with capacity of `[70, 90, 60]`. Set `random_state=17`. Display the environment.

In [ ]:
knapsack = Knapsack(num_items=100, capacity=[70,90,60], random_state=17)

knapsack.display()

Knapsack Capacity: [70, 90, 60]
Current Weight:    [0 0 0]
Current Value:     0
Is Valid Solution: False



## 1.B - Apply Genetic Algorithm

The optimal solution to this problem has a value of 417. The genetic algorithm can find this solution relatively quickly with the correct parameters. You will be asked to attempt to find this solution.

Create an instance of the `GeneticAlgorithm` class for the `Knapsack` instance you created in Step 1.A. Set a population size of 1000, and initialize all members of the population to have all zero values. For the sake of reproducibility, set `random_state` to a value of your choice.

Call the `run_evolution()` method to apply the genetic algorithm to the Knapsack environment setting `num_generations=200` and `update_rate=50`. Experiment with the reproduction rate and mutation rate until you find an optimal solution to the problem.



In [ ]:
gal = GeneticAlgorithm(env=knapsack, pop_size=1000, init_zero=True, random_state=42)

soln = gal.run_evolution(num_generations=200, update_rate=50, rr=.3, mr=1e-3)

Generation 001: New best score found! Current best score = 50
Generation 002: New best score found! Current best score = 88
Generation 007: New best score found! Current best score = 94
Generation 008: New best score found! Current best score = 112
Generation 009: New best score found! Current best score = 118
Generation 010: New best score found! Current best score = 125
Generation 011: New best score found! Current best score = 146
Generation 012: New best score found! Current best score = 175
Generation 014: New best score found! Current best score = 193
Generation 016: New best score found! Current best score = 249
Generation 017: New best score found! Current best score = 252
Generation 023: New best score found! Current best score = 257
Generation 024: New best score found! Current best score = 267
Generation 025: New best score found! Current best score = 276
Generation 026: New best score found! Current best score = 292
Generation 027: New best score found! Current best score =

## 1.C - Display the Solution

Use the `display()` method to display the solution found in Step 1.B.

In [ ]:
soln.display()

Knapsack Capacity: [70, 90, 60]
Current Weight:    [67 80 60]
Current Value:     417
Is Valid Solution: True



# Part 2: Job Assignment (Search Algorithms)

In Part 2, you will apply the search algorithms covered in Weeks 1 and 2 to two different instances of the Job Assignment problem.

## 2.A - Create Environment

Create an instance of the `JobAssignment` environment with 3 jobs, 8 workers, and a maximum worker skill of 10. Set `random_state=1`. Display the environment.


In [ ]:
job01 = JobAssignment(n_jobs=3, n_workers=8, max_skill=10, random_state=1)
job01.display()

Job Requirements: [ 0 12 13  9]
Worker Costs:     [4 9 8 4 7 6 2 4]

Worker Skills:    
[[ 0  0  0  0  0  0  0  0]
 [ 3  5  6  3  5  3  5  8]
 [ 8 10  2  8  1  7 10 10]
 [ 8  7 10  2  1  2  9  9]]

Assignments:      [ _ _ _ _ _ _ _ _ ]
Total cost: 0



## 2.B - Applying Search Algorithms

Apply the 5 search algorithms from Weeks 1 and 2 to the JobAssignment instance created in Step 2.A. Set a time limit of 2 minutes for each search algorithm. Note that some of the algorithms may not find a solution within 2 minutes.

In [ ]:
soln01, log01 = depth_first_search(env=job01, time_limit=120)
soln02, log02 = breadth_first_search(env=job01, time_limit=120)
soln03, log03 = uniform_cost_search(env=job01, time_limit=120)
soln04, log04 = greedy_best_first(env=job01, time_limit=120)
soln05, log05 = astar_search(env=job01, time_limit=120)

[DFS] Solution found.
1840 nodes seen.
1125 nodes skipped
623 nodes expanded.
92 nodes remaining in frontier.
0.04 seconds elapsed.
Assignments: [ 1 2 1 2 1 3 3 3 ]
Job Reqs:    [ 0 12 13  9]
Total Skill: [ 0 14 18 20]
Total Cost:  44

[BFS] Solution found.
123109 nodes seen.
28971 nodes skipped
10496 nodes expanded.
83642 nodes remaining in frontier.
2.11 seconds elapsed.
Assignments: [ 2 1 3 2 _ _ _ 1 ]
Job Reqs:    [ 0 12 13  9]
Total Skill: [ 0 13 16 10]
Total Cost:  29

[UCS] Solution found.
56560 nodes seen.
9595 nodes skipped
4331 nodes expanded.
42634 nodes remaining in frontier.
0.88 seconds elapsed.
Assignments: [ 2 _ _ 2 1 _ 3 1 ]
Job Reqs:    [ 0 12 13  9]
Total Skill: [ 0 13 16  9]
Total Cost:  21

[GBF] Solution found.
91 nodes seen.
0 nodes skipped
6 nodes expanded.
85 nodes remaining in frontier.
0.0 seconds elapsed.
Assignments: [ _ 2 3 _ 1 _ 2 1 ]
Job Reqs:    [ 0 12 13  9]
Total Skill: [ 0 13 20 10]
Total Cost:  30

[AST] Solution found.
9928 nodes seen.
1030 nodes s

## 2.C - Create Environment

Create an instance of the `JobAssignment` environment with 4 jobs, 10 workers, and a maximum worker skill of 12. Set `random_state=1`. Display the environment.


In [ ]:
job02 = JobAssignment(n_jobs=4, n_workers=10, max_skill=12, random_state=1)
job02.display()

Job Requirements: [ 0 12 13  9 16]
Worker Costs:     [5 1 4 3 1 5 3 8 8 9]

Worker Skills:    
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 5  6  3  5 12 11  3  5  8  8]
 [10  2  8  1  7 10 10  8  7 10]
 [ 2  1  2  9  9  4 11 10  9  8]
 [ 4  7  6  2 10  4  5  9  2 12]]

Assignments:      [ _ _ _ _ _ _ _ _ _ _ ]
Total cost: 0



## 2.D - Applying Search Algorithms

Apply the 5 search algorithms from Weeks 1 and 2 to the JobAssignment instance created in Step 2.C. Set a time limit of 2 minutes for each search algorithm. Note that some of the algorithms may not find a solution within 2 minutes.

In [ ]:
soln01, log01 = depth_first_search(env=job02, time_limit=120)
soln02, log02 = breadth_first_search(env=job02, time_limit=120)
soln03, log03 = uniform_cost_search(env=job02, time_limit=120)
soln04, log04 = greedy_best_first(env=job02, time_limit=120)
soln05, log05 = astar_search(env=job02, time_limit=120)

[DFS] Solution found.
6601 nodes seen.
4336 nodes skipped
2063 nodes expanded.
202 nodes remaining in frontier.
0.12 seconds elapsed.
Assignments: [ 2 4 2 3 1 4 4 4 4 4 ]
Job Reqs:    [ 0 12 13  9 16]
Total Skill: [ 0 12 18  9 39]
Total Cost:  47

[BFS] No solution was found.
Time limit reached.
7081161 nodes seen.
1275112 nodes skipped
344649 nodes expanded.
5461400 nodes remaining in frontier.
120.0 seconds elapsed.

[UCS] Solution found.
2400249 nodes seen.
408734 nodes skipped
114995 nodes expanded.
1876520 nodes remaining in frontier.
42.97 seconds elapsed.
Assignments: [ _ 4 2 3 1 _ 2 4 _ _ ]
Job Reqs:    [ 0 12 13  9 16]
Total Skill: [ 0 12 18  9 16]
Total Cost:  20

[GBF] Solution found.
197 nodes seen.
0 nodes skipped
8 nodes expanded.
189 nodes remaining in frontier.
0.02 seconds elapsed.
Assignments: [ _ 4 _ _ 1 1 2 4 3 2 ]
Job Reqs:    [ 0 12 13  9 16]
Total Skill: [ 0 23 20  9 16]
Total Cost:  35

[AST] Solution found.
415489 nodes seen.
47930 nodes skipped
16878 nodes exp

# Part 3: Job Assignment (Genetic Algorithm)

In Part 3, you will apply the genetic algorithm to the Job Assignment problems that you considered in Part 2.

In each case, you will be asked to adjust the Genetic Algorithm parameters in an attempt to obtain an optimal solution.

Recall that the search algorithms score solutions based on **cost** while the genetic algorithm scores solutions based on **fitness**. In order to compare the solutions, recall that the fitness score for solutions to the Job Assignment problem is calculated as shown below

    fitness = 10 * num_workers - total_cost

## 3.A - Apply Genetic Algorithm

Create an instance of the `GeneticAlgorithm` class for the `JobAssignment` instance you created in Step 2.A. Set a population size of 1000. For the sake of reproducibility, set a `random_state` to a value of your choice.

Call the `run_evolution()` method to apply the genetic algorithm to the Knapsack environment setting `num_generations=100` and `update_rate=50`. Experiment with the reproduction rate and mutation rate until you find an optimal solution to the problem.



In [ ]:
gal02 = GeneticAlgorithm(env=job01, pop_size=1000, init_zero=False, random_state=42)

soln = gal02.run_evolution(num_generations=100, update_rate=50, rr=.5, mr=1e-2)

Generation 001: New best score found! Current best score = 53
Generation 008: New best score found! Current best score = 57
Generation 030: New best score found! Current best score = 58
Generation 042: New best score found! Current best score = 59
Generation 050: Q1=0, Med=0, Q3=0, Max=59
Generation 100: Q1=0, Med=0, Q3=0, Max=59


## 3.B - Display the Solution

Use the `display()` method to show the details of the solution found in Step 3.A.Set `flags='rcat'` when calling `display()`. This will simplify the output by hiding the workers skills array.

In [ ]:
soln.display(flags='rcat')

Job Requirements: [ 0 12 13  9]
Worker Costs:     [4 9 8 4 7 6 2 4]
Assignments:      [ 2 _ _ 2 1 _ 3 1 ]
Total cost: 21



## 3.C - Apply Genetic Algorithm

Create an instance of the `GeneticAlgorithm` class for the `JobAssignment` instance you created in Step 2.A. Set a population size of 1000. For the sake of reproducibility, set a `random_state` to a value of your choice.

Call the `run_evolution()` method to apply the genetic algorithm to the Knapsack environment setting `num_generations=200` and `update_rate=50`. Experiment with the reproduction rate and mutation rate until you find an optimal solution to the problem.

In [ ]:
gal03 = GeneticAlgorithm(env=job02, pop_size=1000, init_zero=False, random_state=42)

soln = gal03.run_evolution(num_generations=200, update_rate=50, rr=.5, mr=1e-2)

Generation 001: New best score found! Current best score = 70
Generation 016: New best score found! Current best score = 73
Generation 037: New best score found! Current best score = 74
Generation 044: New best score found! Current best score = 75
Generation 050: Q1=0, Med=0, Q3=0, Max=74
Generation 066: New best score found! Current best score = 77
Generation 070: New best score found! Current best score = 79
Generation 100: Q1=0, Med=0, Q3=0, Max=79
Generation 150: Q1=0, Med=0, Q3=0, Max=79
Generation 157: New best score found! Current best score = 80
Generation 200: Q1=0, Med=0, Q3=0, Max=79


## 3.D - Display the Solution

Use the `display()` method to show the details of the solution found in Step 3.C.Set `flags='rcat'` when calling `display()`. This will simplify the output by hiding the workers skills array.

In [ ]:
soln.display(flags='rcat')

Job Requirements: [ 0 12 13  9 16]
Worker Costs:     [5 1 4 3 1 5 3 8 8 9]
Assignments:      [ _ 4 2 3 1 _ 2 4 _ _ ]
Total cost: 20



# Part 4: Large Job Assignment Problem

You should have observed in Parts 2 and 3 that the genetic algorithm is capable of finding optimal solutions to the job assignment problem much more quickly that the search algorithms. In Part 4, you will apply the genetic algorithm to a large job assignment problem that the optimal search algorithms would have no hope of solving in a reasonable amount of time.


## 4.A - Create Environment

Create an instance of the `JobAssignment` environment with 10 jobs, 50 workers, and a maximum worker skill of 5. Set `random_state=1`. Display the environment.


In [ ]:
job03 = JobAssignment(n_jobs=10, n_workers=50, max_skill=5, random_state=1)

job03.display()

Job Requirements: [ 0 12 13  9 16 10 12  6 16  1  1]
Worker Costs:     [8 2 2 5 7 6 7 5 2 2 6 2 3 7 3 4 4 3 4 1 1 2 6 1 6 9 9 1 1 1 9 6 4 5 1 9 7 4 1 9 2 7 7 2 4 8 4 3 4 1]

Worker Skills:    
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [2 1 2 4 5 4 2 4 1 1 3 3 2 4 5 3 1 1 2 2 4 1 1 5 3 5 4 4 1 4 5 4 5 5 5 2 1 5 3 1 3 5 2 2 1 3 5 5 1 5]
 [2 5 2 1 3 4 2 3 5 5 3 3 1 2 3 3 1 2 3 5 1 2 3 2 5 3 1 1 2 1 2 4 2 2 5 5 4 1 4 1 4 2 3 5 1 1 4 2 2 1]
 [1 5 3 4 5 3 1 4 4 2 3 5 4 1 1 5 3 5 3 1 4 1 1 5 3 2 1 5 4 1 2 3 5 5 4 4 4 4 3 4 4 5 4 3 5 5 1 4 4 1]
 [4 2 1 3 3 3 1 3 2 5 1 5 5 2 4 2 5 2 3 2 1 1 3 5 2 1 1 4 2 1 5 4 3 4 5 5 4 1 1 1 5 2 5 2 3 3 5 4 5 5]
 [1 4 3 5 4 5 3 4 1 3 2 4 3 1 2 5 2 4 4 2 3 1 3 5 1 3 5 4 5 4 1 5 3 3 5 2 3 2 2 2 1 5 5 3 3 4 2 5 1 1]
 [4 3 5 2 4 2 2 3 5 1 4 1 5 3 4 2 2 5 5 1 3 2 4 1 2 1 3 3 5 4 3 3 3 1 3 1 5 2 1 3 4 1 5 4 4 4 1 4 2 3]
 [1 2 5 3 4 5 5 3 2 3 1 4 4 3 1 1 1 1 3 5 1 5 2 3 2 3 5 2 4 2 2 3 5 2 1 3 2 3 1 1 4 5 

## 4.B - Greedy Best First Search

You should have noticed in Part 2 that Greedy Best First Search can find decent, but not optimal, solutions to the job assignment quickly. We will use GBF as a benchmark to compare against the solutions found by the genetic algorithm.

In the next cell, apply Greedy Best First search to the environment created in Step 4.A. Set a time limit of 2 minutes.

In [ ]:
soln01, log01 = greedy_best_first(env=job03, time_limit=120)

[GBF] Solution found.
9501 nodes seen.
0 nodes skipped
26 nodes expanded.
9475 nodes remaining in frontier.
0.58 seconds elapsed.
Assignments: [ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 8 _ _ _ _ _ _ 8 8 _ _ _ 7 8 9 10 1 1 4 2 6 1 2 6 4 5 6 2 3 3 4 5 7 4 ]
Job Reqs:    [ 0 12 13  9 16 10 12  6 16  1  1]
Total Skill: [ 0 15 14 10 20 10 13  9 18  5  2]
Total Cost:  110



## 4.C - Apply Genetic Algorithm

Create an instance of the `GeneticAlgorithm` class for the `JobAssignment` instance you created in Step 2.A. Set a population size of 1000. For the sake of reproducibility, set a `random_state` to a value of your choice.

Call the `run_evolution()` method to apply the genetic algorithm to the Knapsack environment setting `num_generations` to be 3000 or less and setting `update_rate=500`. Experiment with the reproduction rate and mutation rate until you find a solution **with a cost of 80 or less**.

**Note:** You are not required to find an optimal solution to this enviornmnet. But in case you want to try, the cost for an optimal solution is 53.

In [ ]:
gal04 = GeneticAlgorithm(env=job03, pop_size=1000, init_zero=False, random_state=42)

soln =  gal04.run_evolution(num_generations=3000, update_rate=500, rr=.45, mr=1e-3)

Generation 0001: New best score found! Current best score = 309
Generation 0030: New best score found! Current best score = 313
Generation 0041: New best score found! Current best score = 315
Generation 0054: New best score found! Current best score = 317
Generation 0072: New best score found! Current best score = 322
Generation 0392: New best score found! Current best score = 326
Generation 0397: New best score found! Current best score = 333
Generation 0500: Q1=0, Med=0, Q3=0, Max=320
Generation 0504: New best score found! Current best score = 336
Generation 0610: New best score found! Current best score = 338
Generation 0612: New best score found! Current best score = 343
Generation 0669: New best score found! Current best score = 346
Generation 0706: New best score found! Current best score = 349
Generation 0728: New best score found! Current best score = 350
Generation 0732: New best score found! Current best score = 352
Generation 0734: New best score found! Current best score = 

## 4.D - Display the Solution

Use the `display()` method to show the details of the solution found in Step 3.C.Set `flags='rcat'` when calling `display()`. This will simplify the output by hiding the workers skills array.

In [ ]:
soln.display(flags='rcat')

Job Requirements: [ 0 12 13  9 16 10 12  6 16  1  1]
Worker Costs:     [8 2 2 5 7 6 7 5 2 2 6 2 3 7 3 4 4 3 4 1 1 2 6 1 6 9 9 1 1 1 9 6 4 5 1 9 7 4 1 9 2 7 7 2 4 8 4 3 4 1]
Assignments:      [ _ 8 _ 10 _ _ _ 1 6 2 _ 4 4 _ 8 _ 4 3 6 7 9 8 _ 8 2 _ _ 6 5 6 _ _ _ _ 5 _ _ 7 1 _ 4 _ _ 2 3 _ 1 5 _ 7 ]
Total cost: 71



# Submission Instructions

1. Perform a Restart and Run All by clicking **Tools > Restart session and run all**.
2. Copy the link to your notebook by clicking **Share > Copy Link**.
3. Paste the copied link into the `notebook_url` field in the [Notebook Renderer](https://colab.research.google.com/drive/1CJTipys46ldZxJFwnt7XbdjQUfkmoXeU?usp=sharing) tool and then execute the cell to render the notebook.
4. The Notebook Renderer will open up a save file dialog. Save the resulting HTML file yo your local machine.
5. Submit the HTML file to Canvas.
